version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - apps-dock-network

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - apps-dock-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: laravel
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - apps-dock-network

networks:
  apps-dock-network:
    driver: bridge

volumes:
  dbdata:
